use printpdf::*;
use serde::{Deserialize, Serialize};
use std::fs::File;
use std::io::BufWriter;
use tracing::info;

/// Data structure for generating a risk assessment PDF report.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportData {
    pub title: String,
    pub generated_date: String,
    pub portfolio_name: String,
    pub total_properties: usize,
    pub total_tiv: Option<f64>,
    pub geocoded_count: usize,
    pub risk_summaries: Vec<ReportRiskSummary>,
    pub top_exposures: Vec<Vec<String>>,
    pub top_exposure_columns: Vec<String>,
}

/// Risk summary for a single risk layer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportRiskSummary {
    pub layer_name: String,
    pub zone_breakdown: Vec<(String, usize, f64)>, // (zone_name, property_count, total_tiv)
}

/// Generate a PDF risk assessment report and write it to `output_path`.
pub fn generate_risk_report(
    data: &ReportData,
    output_path: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let (doc, page1, layer1) = PdfDocument::new(&data.title, Mm(210.0), Mm(297.0), "Layer 1");

    let font = doc.add_builtin_font(BuiltinFont::Helvetica)?;
    let font_bold = doc.add_builtin_font(BuiltinFont::HelveticaBold)?;

    // === PAGE 1: Title + Summary ===
    let current_layer = doc.get_page(page1).get_layer(layer1);

    // Title
    current_layer.use_text(&data.title, 22.0, Mm(20.0), Mm(270.0), &font_bold);

    // Date and portfolio info
    current_layer.use_text(
        format!("Generated: {}", data.generated_date),
        10.0,
        Mm(20.0),
        Mm(256.0),
        &font,
    );
    current_layer.use_text(
        format!("Portfolio: {}", data.portfolio_name),
        10.0,
        Mm(20.0),
        Mm(248.0),
        &font,
    );

    // Summary statistics
    let mut y: f32 = 230.0;
    current_layer.use_text("Summary Statistics", 14.0, Mm(20.0), Mm(y), &font_bold);
    y -= 12.0;

    let stats = vec![
        format!("Total Properties: {}", data.total_properties),
        format!(
            "Total Insured Value: {}",
            match data.total_tiv {
                Some(tiv) => format!("${:.0}", tiv),
                None => "N/A".to_string(),
            }
        ),
        format!(
            "Geocoded: {} / {} ({:.1}%)",
            data.geocoded_count,
            data.total_properties,
            if data.total_properties > 0 {
                data.geocoded_count as f64 / data.total_properties as f64 * 100.0
            } else {
                0.0
            }
        ),
        format!("Risk Layers Analyzed: {}", data.risk_summaries.len()),
    ];

    for stat in &stats {
        current_layer.use_text(stat, 10.0, Mm(25.0), Mm(y), &font);
        y -= 8.0;
    }

    // Risk summaries
    if !data.risk_summaries.is_empty() {
        y -= 12.0;
        current_layer.use_text("Risk Zone Analysis", 14.0, Mm(20.0), Mm(y), &font_bold);
        y -= 14.0;

        for summary in &data.risk_summaries {
            if y < 50.0 {
                break; // Don't overflow page
            }

            current_layer.use_text(&summary.layer_name, 11.0, Mm(25.0), Mm(y), &font_bold);
            y -= 10.0;

            // Column headers
            current_layer.use_text("Zone", 9.0, Mm(30.0), Mm(y), &font_bold);
            current_layer.use_text("Properties", 9.0, Mm(100.0), Mm(y), &font_bold);
            current_layer.use_text("Total TIV", 9.0, Mm(140.0), Mm(y), &font_bold);
            y -= 7.0;

            for (zone, count, tiv) in &summary.zone_breakdown {
                if y < 30.0 {
                    break;
                }
                current_layer.use_text(zone, 9.0, Mm(30.0), Mm(y), &font);
                current_layer.use_text(count.to_string(), 9.0, Mm(100.0), Mm(y), &font);
                current_layer.use_text(format!("${:.0}", tiv), 9.0, Mm(140.0), Mm(y), &font);
                y -= 6.0;
            }
            y -= 6.0;
        }
    }

    // Footer
    current_layer.use_text(
        "Generated by Spatia — AI-Powered Spatial Risk Intelligence",
        8.0,
        Mm(20.0),
        Mm(15.0),
        &font,
    );

    // === PAGE 2: Top Exposures table (if data exists) ===
    if !data.top_exposures.is_empty() && !data.top_exposure_columns.is_empty() {
        let (page2, layer2) = doc.add_page(Mm(210.0), Mm(297.0), "Layer 1");
        let current_layer2 = doc.get_page(page2).get_layer(layer2);

        current_layer2.use_text("Top Exposures", 14.0, Mm(20.0), Mm(270.0), &font_bold);

        let mut y2: f32 = 255.0;
        let col_count = data.top_exposure_columns.len().min(6); // Max 6 columns
        let col_width: f32 = 170.0 / col_count as f32;

        // Headers
        for (i, col_name) in data.top_exposure_columns.iter().take(col_count).enumerate() {
            let x: f32 = 20.0 + (i as f32 * col_width);
            let display = if col_name.len() > 18 {
                &col_name[..18]
            } else {
                col_name
            };
            current_layer2.use_text(display, 8.0, Mm(x), Mm(y2), &font_bold);
        }
        y2 -= 8.0;

        // Data rows
        for row in &data.top_exposures {
            if y2 < 20.0 {
                break;
            }
            for (i, val) in row.iter().take(col_count).enumerate() {
                let x: f32 = 20.0 + (i as f32 * col_width);
                let display = if val.len() > 22 { &val[..22] } else { val };
                current_layer2.use_text(display, 8.0, Mm(x), Mm(y2), &font);
            }
            y2 -= 5.0;
        }

        // Footer
        current_layer2.use_text(
            "Generated by Spatia — AI-Powered Spatial Risk Intelligence",
            8.0,
            Mm(20.0),
            Mm(15.0),
            &font,
        );
    }

    // Save the PDF
    doc.save(&mut BufWriter::new(File::create(output_path)?))?;

    info!(output_path, "Risk assessment report generated successfully");
    Ok(())
}
